### ISSUE TITLE
Can no longer get messages in the latest version

### ISSUE THREAD

**Issue by dstelzer** [carpedm20/fbchat#385]
## Description of the problem
Attempting to get any messages fails with an AttributeError.

## Traceback
```
[Lots of tracebacks falling through down to…]
    ms = self.client.fetchThreadMessages(thread, lim, before=self.laststamp)
  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 847, in fetchThreadMessages
    messages = list(reversed([graphql_to_message(message) for message in j['message_thread']['messages']['nodes']]))
  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 847, in <listcomp>
    messages = list(reversed([graphql_to_message(message) for message in j['message_thread']['messages']['nodes']]))
  File "/usr/local/lib/python3.6/dist-packages/fbchat/graphql.py", line 294, in graphql_to_message
    attachment = graphql_to_extensible_attachment(message['extensible_attachment'])
  File "/usr/local/lib/python3.6/dist-packages/fbchat/graphql.py", line 171, in graphql_to_extensible_attachment
    description=story['description'].get('text'),
AttributeError: 'NoneType' object has no attribute 'get'
```

## Environment information
- Python 3.6.7
- `fbchat` 1.5.0

**Comment by madsmtm** [comment]
_Any_ message? Or just specific ones?

No matter what, this error is probably introduced in #333. @kapi2289, can you solve this one?

**Comment by dstelzer** [comment]
At the moment this happens when I fetch from any conversation that has messages in it.
